import type { ProjectConfig } from "../types";

export const defaultConfig: ProjectConfig = {
  projectPath: "",
  workspace: "",
  xcodeproj: "",
  schemeDev: "",
  schemeDis: "",
  bundleIdDev: "",
  bundleIdDis: "",
  teamId: "",
  profileDev: "",
  profileDis: "",
  signingStyle: "automatic",
  matchGitUrl: "",
  matchGitBranch: "main",
  pgyerApiKey: "",
  appStoreConnectApiKeyPath: "",
  enableQualityGate: true,
  enableTests: true,
  enableSwiftlint: false,
  enableSlackNotify: false,
  enableWechatNotify: false,
  enableSnapshot: false,
  snapshotScheme: "",
  snapshotDevices: "",
  snapshotLanguages: "",
  metadataPath: "fastlane/metadata",
  enableMetadataUpload: false,
  enableScreenshotUpload: false,
  gymSkipClean: false,
  derivedDataPath: "",
  ciBundleInstall: true,
  ciCocoapodsDeployment: true,
  bootstrapMode: "standard",
  bootstrapConfigPath: ""
};
